package com.logica.ngph.common.dtos;


/**
 * 
 * @author mohdabdulaa
 *
 */
public class ChargesDetailsDto {
	
	//The unique reference 
	//for every payment - generated by NGPH and that maps to the message details table
	//@MSGCHGS_MSGREF
	private String msgRef;
	
	//The BIC of the bank that has levied the charge
	//@MSGCHGS_CHRGSINF_PTY_BKCD
	private String chargingPartyBank;
	
	//The currency of the charge
	//@MSGCHGS_CHRGSINF_CCY
	private String chargeCurrency;
	
	//Amount of charges
	//@MSGCHGS_CHRGSINF_AMT
	private String chargeAmount;

	/**
	 * @return the msgRef
	 */
	public String getMsgRef() {
		return msgRef;
	}

	/**
	 * @param msgRef the msgRef to set
	 */
	public void setMsgRef(String msgRef) {
		this.msgRef = msgRef;
	}

	/**
	 * @return the chargingPartyBank
	 */
	public String getChargingPartyBank() {
		return chargingPartyBank;
	}

	/**
	 * @param chargingPartyBank the chargingPartyBank to set
	 */
	public void setChargingPartyBank(String chargingPartyBank) {
		this.chargingPartyBank = chargingPartyBank;
	}

	/**
	 * @return the chargeCurrency
	 */
	public String getChargeCurrency() {
		return chargeCurrency;
	}

	/**
	 * @param chargeCurrency the chargeCurrency to set
	 */
	public void setChargeCurrency(String chargeCurrency) {
		this.chargeCurrency = chargeCurrency;
	}

	/**
	 * @return the chargeAmount
	 */
	public String getChargeAmount() {
		return chargeAmount;
	}

	/**
	 * @param chargeAmount the chargeAmount to set
	 */
	public void setChargeAmount(String chargeAmount) {
		this.chargeAmount = chargeAmount;
	}
}
